apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-dapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-dapp
  template:
    metadata:
      labels:
        app: my-dapp
    spec:
      containers:
        - name: my-dapp-container
          image: athikaf/my-dapp:5.0
          ports:
            - containerPort: 4000
          resources:
            requests:
              memory: 64Mi
              cpu: 250m
            limits:
              memory: 64Mi
              cpu: 250m
          volumeMounts:
            - name: app-storage
              mountPath: /var # Adjust the mount path based on your application's storage requirements
      volumes:
        - name: app-storage
          persistentVolumeClaim:
            claimName: app-pvc
